# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PSAUI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PSAUI
  pod 'PSACommon', '~> 1.0.2'

end
